import discord
import random
import requests
import json

client = discord.Client()

# function that gets quotes that uses module request and json to work to
# get the random quote generated by the api site
def get_quote():
  response = requests.get("https://zenquotes.io/api/random")
  json_data = json.loads(response.text)
  quote = json_data[0]['q'] + " -" + json_data[0]['a']
  return(quote)

@client.event
async def on_ready():
    print('We have logged in as {0.user}'.format(client))


@client.event
async def on_message(message):
    if message.author == client.user:
        return
# list of commands that users can use
    commandlist = "$command, $hello, $bye, $rolld6, $inspire"

# the following if statements are the commands that users use the bot response the reply using the await
# command giving the user a response

    if message.content.startswith('$command'):
        await message.channel.send('The Following commands are: '+ commandlist)

    if message.content.startswith('$hello'):
        await message.channel.send('Hello!')

    if message.content.startswith('$bye'):
        await message.channel.send('Goodbye')

    if message.content.startswith('$rolld6'):
        await message.channel.send('Rolling')
        await message.channel.send(random.randint(1,7))

    if message.content.startswith('$rolld20'):
        await message.channel.send('Rolling')
        await message.channel.send(random.randint(1,21))

    if message.content.startswith('$inspire'):
        quote = get_quote()
        await message.channel.send(quote)


# the client/bot signature token is used here to activate the bot calling the discord server
client.run('insert token here')
